name: quake_safe_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.4+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.0
  authentication_repository:
    path: ./packages/authentication_repository
  auto_route: ^7.8.4
  bloc: ^8.1.2
  boxy: ^2.2.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  dio: ^5.4.0
  extended_image: ^8.2.0
  faker: ^2.1.0
  flash: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_geojson: ^1.0.6
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  geoxml: ^2.5.2
  google_fonts: ^6.1.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  posts_repository:
    path: ./packages/posts_repository
  quake_safe_platform_client:
    path: ./packages/quake_safe_platform_client
  reactive_forms: ^16.1.1
  supabase_flutter: ^2.3.3
  timeago: ^3.6.1
  user_repository:
    path: ./packages/user_repository

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - .env
    - .env.development
    - .env.staging
